### ISSUE TITLE
Remarks on Setup app

### ISSUE THREAD

**Issue by srdjastankovic** [Wolkabout/offset-printing-machine-simulator-application#2]
Offset Printing Machine HMI, with Modbus TCP repo remarks:

- navigate to repo folder
- make executable depencency.sh
- "Setting up QT Creator" section as separate section nad mention it is for someone who wants to modify exmaple for runing it isn't neccesary. Mandatory: link it to downlaod page of QT Creator open source.
 - Update dependency.sh: sudo apt install libmodbus-dev=3.1.4-2

**Comment by ghost** [comment]
Solved with https://github.com/Wolkabout/offset-printing-machine-simulator-application/pull/3
